execute pathogen#infect()
syntax on
autocmd vimenter * NERDTree
colorscheme iceberg 
"set bg=dark
let g:airline_theme = 'dark'
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'typescript': ['tsserver', 'tslint']
\}

" Keep Plug commands between plug#begin() and plug#end().
call plug#begin()

" AUTOCOMPLETION
Plug 'neoclide/coc.nvim' , { 'branch' : 'release' }
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'leafgarland/typescript-vim'
Plug 'HerringtonDarkholme/yats'

call plug#end()

let g:coc_global_extensions = [ 'coc-tsserver' ]
filetype plugin indent on

" set path variables
let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"
let $DEV="~/Documents/Development"
let $WO="$HOME/Desygner"
let $GL="~/Documents/Development/JavaScript/github-repos/glance-app"
let $N="~/Documents/Notes/tbfollowup.md"
let $Z="~/.zshrc"

" random settings
let g:coc_disable_startup_warning = 1
set path=.,**
set re=0

" Indentation
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent
set smartindent

" Ruler
setlocal colorcolumn=80

" Numbers
set number
set numberwidth=4
set ruler

" Delete characters outside of insert area
set backspace=indent,eol,start

" Disable backups and swap files
set nobackup
set nowritebackup
set noswapfile

" ENABLE search options
set is
" set hls

" NERDTREE
let NERDTreeMapOpenInTab='<Right>'

" SET LEADER (PREFIX)
:let mapleader = ","

" KEYMAPPINGS FOR NAVIGATION
nnoremap <leader>ev :split $MYVIMRC<cr>
nnoremap <leader>so :so $MYVIMRC<cr>
nnoremap H 0
nnoremap L A<esc>

" KEYMAPPINGS
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-f> :Files<CR>
nnoremap - ddp
nnoremap _ ddkP
nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
inoremap <c-u> <esc>vawU

" ABBREVIATIONS
:iabbrev calss class
:iabbrev eclass export class {}
" INCLUDE SEARCH
" ^\s*\(import\|require\)\s*\({\)\s*\zs\(\S\+\s\{-}\)

